name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server
              env:
                  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
                  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
              run: |
                  ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
                  cd /var/www/jobesta
                  sudo git reset --hard origin/main
                  sudo git pull origin main --force
                  cp server/.env server/.env.example
                  cp client/.env client/.env.example
                  sudo docker-compose up -d --build
                  EOF
